apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vnext-mockoon-pubsub
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: vnext-redis:6379
  - name: redisPassword
    value: ""