apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vnext-notification-binding
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: http://mockoon:3001/api/notification/send
    