apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vnext-execution-state
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: vnext-redis:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "false"
  - name: keyPrefix
    value: "vnext"