apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vnext-secret
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
    - name: vaultAddr
      value: http://vnext-vault:8200
    - name: vaultToken
      value: "admin"
    - name: skipVerify
      value: true
    - name: vaultKVUsePrefix
      value: false
    - name: vaultKVPrefix
      value: workflow-secret
    - name: enginePath
      value: "secret"
    - name: vaultValueType
      value: "map"